backend:
  name: git-gateway

publish_mode: editorial_workflow
display_url: https://biocosm.xyz

slug:
  encoding: "ascii"
  clean_accents: true

media_folder: static/images/uploads
public_folder: images/uploads

collections:
  - name: "blog"
    label: "Blog ----- REMEMBER, due to upstream issues we have weird image stuff going on rn. just do everything like normal, but before you publish, go to Markdown mode and add this on the front of each image source: '../../../static'. like if it says ![alt text](/images/uploads/apig.jpg), make it say ![alt text](../../../static/images/uploads/apig.jpg). the preview will look fucked up but this is a good sign, just publish. see how the images look better and scale to screen size? THANKS MAX"
    folder: "content/posts/uploads"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description:
    fields:
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Publish Date", name: "date", widget: "datetime"}
     - {label: "Cover Image", name: "cover", widget: "file"}
     - {label: "Body", name: "body", widget: "markdown"}
     - {label: "Category", name: "category", widget: "string"}
     - {label: "Author", name: "author", widget: "string"}

  - name: pages
    label: "Pages -- you can't delete these or add more from this interface, but you can edit them"
    delete: false
    files:
      - name: "about"
        label: "About"
        file: "content/pages/1--about/index.md"
        description: "Site Mission and Excuses"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "platform"
        label: "Platform"
        file: "content/pages/2--biocosm/index.md"
        description: "Space Platform Soapbox"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "donate"
        label: "Donate"
        file: "content/pages/3--donate/index.md"
        description: "Money Bucket"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "contribute"
        label: "Contribute"
        file: "content/pages/4--contribute/index.md"
        description: "Give us your tired, your sweaty, your broken iphone"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
